### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by Andrewnolan13** [bpetkov28/image_reshaper#2]
under "clone the repo" you have 
```
git clone https://github.com/yourusername/image_reshaper.git
```
when it should be:
```
https://github.com/bpetkov28/image_reshaper.git
```

also, 
```
pip install -r requirements.txt
```
is redundant because you have no requirements.txt

Nice idea though :)

**Comment by bpetkov28** [comment]
Thank you for your feedback. It's much appreciated. These are now resolved.
